server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
#      force: true

spring:
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    properties: # property 사용 설정
      hibernate: # hibernate property 설정
#        format_sql: true
  #        show_sql: true
  data:
    redis:
      host: localhost
      port: 6379

  devtools:
    add-properties: false

#logging:
#  level:
#    org.hibernate.type: trace                   # 콘솔차에 조건에 바인딩되는 값 및 조회 결과 출력
#    org.hibernate.SQL: debug                    # logger를 통해 하이버네이트 실행 SQL
#    org.hibernate.orm.jdbc.bind: trace  # ? 값 조회

# jwt 설정
jwt:
  issuer: 0157942@gmail.com
  secret_key: nqhMyX%^J%HNDw#2YTbNQkmNiMJKV6HsGh32QbqspYRllzyGI%JXrGpCob@9^FQfo0sNSMnSI5bQfQ7u^XPGNdpUhsHTfwqLUm24Z0uaMlRwY2YfZcXzn6nFL3x85YQUGEbTe6UFUAO806dYk#HwCm2Xe3cTuhl6WBxkRuqbJ7PU7PXSLy0NVbSFQA55RUDx^LKosc1TARI3x5nr2^sZst8gnbqNi%s23SDZbLN3nCwZv#@X8WqvTJ5GX^U1ZDSK

# swagger disable
springdoc:
  swagger-ui:
    enabled: false

